/* ============================================================
   Design System — Tokens (source of truth)
   ============================================================
   Generated by supervibe:brandbook. Every prototype + production
   stack imports from this file. Adding a value requires going
   through supervibe:brandbook (system extension dialogue), not an
   ad-hoc edit in a prototype.
*/

:root {
  /* === COLOR — palette ramps ============================== */
  /* Use semantic aliases (--color-primary, --color-fg, etc.)
     in app code. Direct ramps (--color-primary-500) are for
     the system itself. */

  --color-primary-50:  oklch(0.95 0.02 {{primary-hue}});
  --color-primary-100: oklch(0.90 0.04 {{primary-hue}});
  --color-primary-200: oklch(0.83 0.07 {{primary-hue}});
  --color-primary-300: oklch(0.74 0.11 {{primary-hue}});
  --color-primary-400: oklch(0.65 0.15 {{primary-hue}});
  --color-primary-500: oklch(0.55 0.18 {{primary-hue}}); /* canonical brand */
  --color-primary-600: oklch(0.46 0.16 {{primary-hue}});
  --color-primary-700: oklch(0.38 0.14 {{primary-hue}});
  --color-primary-800: oklch(0.30 0.11 {{primary-hue}});
  --color-primary-900: oklch(0.22 0.08 {{primary-hue}});
  --color-primary-950: oklch(0.15 0.05 {{primary-hue}});

  /* Neutrals (true gray ramp) */
  --color-neutral-50:  oklch(0.98 0 0);
  --color-neutral-100: oklch(0.95 0 0);
  --color-neutral-200: oklch(0.90 0 0);
  --color-neutral-300: oklch(0.83 0 0);
  --color-neutral-400: oklch(0.71 0 0);
  --color-neutral-500: oklch(0.55 0 0);
  --color-neutral-600: oklch(0.43 0 0);
  --color-neutral-700: oklch(0.32 0 0);
  --color-neutral-800: oklch(0.22 0 0);
  --color-neutral-900: oklch(0.14 0 0);
  --color-neutral-950: oklch(0.08 0 0);

  /* Semantic — light mode aliases */
  --color-fg:           var(--color-neutral-900);
  --color-fg-muted:     var(--color-neutral-600);
  --color-fg-subtle:    var(--color-neutral-400);
  --color-bg:           var(--color-neutral-50);
  --color-bg-elevated:  oklch(1 0 0); /* pure white card surface */
  --color-bg-subtle:    var(--color-neutral-100);
  --color-border:       var(--color-neutral-200);
  --color-border-strong: var(--color-neutral-400);
  --color-action:       var(--color-primary-600);
  --color-action-hover: var(--color-primary-700);
  --color-action-fg:    oklch(1 0 0);
  --color-success:      oklch(0.55 0.16 145);
  --color-warning:      oklch(0.70 0.15 75);
  --color-danger:       oklch(0.55 0.20 25);
  --color-info:         oklch(0.60 0.15 220);

  /* === TYPOGRAPHY ========================================= */
  --font-display: '{{display-family|Inter}}', system-ui, sans-serif;
  --font-body:    '{{body-family|Inter}}', system-ui, sans-serif;
  --font-mono:    '{{mono-family|JetBrains Mono}}', ui-monospace, monospace;

  --text-xs:   0.75rem;   /* 12px */
  --text-sm:   0.875rem;  /* 14px */
  --text-base: 1rem;      /* 16px */
  --text-md:   1.125rem;  /* 18px */
  --text-lg:   1.25rem;   /* 20px */
  --text-xl:   1.5rem;    /* 24px */
  --text-2xl:  1.875rem;  /* 30px */
  --text-3xl:  2.25rem;   /* 36px */
  --text-4xl:  3rem;      /* 48px */
  --text-5xl:  3.75rem;   /* 60px */
  --text-6xl:  4.5rem;    /* 72px */

  --leading-tight:  1.1;
  --leading-snug:   1.25;
  --leading-normal: 1.5;
  --leading-relaxed: 1.7;

  --weight-regular: 400;
  --weight-medium:  500;
  --weight-semibold: 600;
  --weight-bold:    700;

  /* === SPACING + SIZING =================================== */
  --space-0:   0;
  --space-1:   0.25rem;   /* 4px  */
  --space-2:   0.5rem;    /* 8px  */
  --space-3:   0.75rem;   /* 12px */
  --space-4:   1rem;      /* 16px */
  --space-5:   1.25rem;   /* 20px */
  --space-6:   1.5rem;    /* 24px */
  --space-8:   2rem;      /* 32px */
  --space-10:  2.5rem;    /* 40px */
  --space-12:  3rem;      /* 48px */
  --space-16:  4rem;      /* 64px */
  --space-20:  5rem;      /* 80px */
  --space-24:  6rem;      /* 96px */
  --space-32:  8rem;      /* 128px */

  /* === RADIUS ============================================= */
  --radius-none: 0;
  --radius-sm:   0.25rem;  /* 4px  */
  --radius-md:   0.5rem;   /* 8px  */
  --radius-lg:   1rem;     /* 16px */
  --radius-xl:   1.5rem;   /* 24px */
  --radius-pill: 9999px;
  --radius-circle: 50%;

  /* === ELEVATION (shadow) ================================== */
  --shadow-none: none;
  --shadow-sm:   0 1px 2px 0 rgb(0 0 0 / 0.05);
  --shadow-md:   0 4px 6px -1px rgb(0 0 0 / 0.10), 0 2px 4px -2px rgb(0 0 0 / 0.10);
  --shadow-lg:   0 10px 15px -3px rgb(0 0 0 / 0.10), 0 4px 6px -4px rgb(0 0 0 / 0.10);
  --shadow-xl:   0 20px 25px -5px rgb(0 0 0 / 0.10), 0 8px 10px -6px rgb(0 0 0 / 0.10);
}

/* === DARK MODE OVERLAY ==================================== */
@media (prefers-color-scheme: dark) {
  :root {
    --color-fg:          var(--color-neutral-100);
    --color-fg-muted:    var(--color-neutral-400);
    --color-fg-subtle:   var(--color-neutral-600);
    --color-bg:          var(--color-neutral-950);
    --color-bg-elevated: var(--color-neutral-900);
    --color-bg-subtle:   var(--color-neutral-900);
    --color-border:      var(--color-neutral-800);
    --color-border-strong: var(--color-neutral-600);
    --color-action-fg:   var(--color-neutral-50);
  }
}
