# CLAUDE.md

> Generated by `evolve:genesis` for stack: **Laravel 11 + Next.js 14 + Postgres + Redis** with bounded contexts: {{bounded-contexts}}

This repository uses the strict Evolve Framework workflow.

## Mission

Deliver correct, minimal, verifiable changes for a **Laravel + Next.js + Postgres + Redis** application.

## Non-negotiable rules

1. Explore first, then plan, then implement, then verify.
2. Do not invent files, commands, routes, events, DTOs, stores, SQL objects, or public contracts.
3. Reuse existing project patterns before creating new abstractions.
4. Keep the **backend ↔ frontend** layer boundary explicit.
5. Do not move business logic into the UI because it is convenient.
6. Prefer incremental changes with reviewable stop points.
7. Do not say a task is done without evidence (`evolve:verification` skill).
8. **Never claim "works correctly" without running a verification command and showing its output.**
9. Every artifact MUST score ≥9 against its `*-quality` rubric (see `evolve:confidence-scoring`).
10. Never use `git stash`/`stash pop`, `push --force`, `reset --hard`, or any banned command (see `.claude/settings.json` deny-list).
11. Conventional Commits enforced via commitlint (`commitlint.config.js`).
12. Pre-commit pipeline enforced via husky (`.husky/`).
13. Zero dead code: every function/struct/variant MUST have ≥1 live call site (see `rules/no-dead-code.md`).

## Project paths (authoritative)

- **Backend (Laravel)**: `backend/`
  - Modules: `backend/app/Modules/{{bounded-contexts}}`
  - Routes: `backend/routes/api.php`, `backend/routes/web.php`
  - Migrations: `backend/database/migrations/`
  - Tests: `backend/tests/Feature/`, `backend/tests/Unit/` (Pest)
- **Frontend (Next.js)**: `frontend/`
  - App router: `frontend/app/`
  - Components: `frontend/components/` (FSD layers)
  - Tests: `frontend/__tests__/`
- **Prototypes**: `prototypes/`
  - **Brandbook (source of truth)**: `prototypes/_brandbook/`
- **Docs**: `docs/`
  - ADRs: `docs/adr/`
  - PRDs: `docs/prd/`
  - Specs: `docs/specs/`
  - Plans: `docs/plans/`

## Agent routing — who to dispatch for what

| Task type | Agent (`subagent_type`) | Skills |
|-----------|------------------------|--------|
| Explore code / find files | `Explore` (built-in) | — |
| Map repo before work | `evolve:_core:repo-researcher` | repo discovery, anti-hallucination |
| Define requirements | `evolve:_product:systems-analyst` | requirements-intake |
| Product / strategy / OKR | `evolve:_product:product-manager` (CPO scope) | prd, adr |
| Backend: modules, services, models | `evolve:stacks/laravel:laravel-developer` | tdd, verification, code-review |
| Backend: architecture | `evolve:stacks/laravel:laravel-architect` (READ-ONLY) | adr |
| Backend: queue jobs | `evolve:stacks/laravel:queue-worker-architect` | adr, debugging |
| Backend: Eloquent models | `evolve:stacks/laravel:eloquent-modeler` | verification |
| Frontend: pages, components | `evolve:stacks/nextjs:nextjs-developer` | tdd, verification, code-review |
| Frontend: architecture | `evolve:stacks/nextjs:nextjs-architect` (READ-ONLY) | adr |
| Frontend: server actions | `evolve:stacks/nextjs:server-actions-specialist` | tdd |
| Database: schema, migrations | `evolve:stacks/postgres:postgres-architect` + `evolve:_ops:db-reviewer` | adr, verification |
| Cache / Redis | `evolve:stacks/redis:redis-architect` | adr |
| AI / LLM integration | `evolve:_ops:ai-integration-architect` | adr |
| Infra: Sentinel, replicas, sharding | `evolve:_ops:infrastructure-architect` | adr |
| Debug / investigate failure | `evolve:_core:root-cause-debugger` | systematic-debugging |
| Code review | `evolve:_core:code-reviewer` | code-review |
| Security audit | `evolve:_core:security-auditor` (READ-ONLY) | code-review |
| Architecture review | `evolve:_core:architect-reviewer` (READ-ONLY) | adr |
| Final quality gate | `evolve:_core:quality-gate-reviewer` | confidence-scoring |
| Refactoring | `evolve:_core:refactoring-specialist` | tdd, code-review |
| Design system / brand direction | `evolve:_design:creative-director` | brandbook |
| Design new screen / UX | `evolve:_design:ux-ui-designer` | prototype |
| HTML prototype builder | `evolve:_design:prototype-builder` | prototype, brandbook |
| UI review / polish | `evolve:_design:ui-polish-reviewer` | confidence-scoring |
| Accessibility review | `evolve:_design:accessibility-reviewer` | confidence-scoring |
| Copy review | `evolve:_design:copywriter` | confidence-scoring |
| QA / test strategy | `evolve:_product:qa-test-engineer` | tdd, verification |
| Analytics tracking | `evolve:_product:analytics-implementation` | confidence-scoring |
| SEO | `evolve:_product:seo-specialist` | seo-audit |
| Email lifecycle | `evolve:_product:email-lifecycle` | confidence-scoring |
| DevOps / SRE / CI/CD | `evolve:_ops:devops-sre` | incident-response, adr |
| Performance | `evolve:_ops:performance-reviewer` (READ-ONLY) | systematic-debugging |
| Dependencies | `evolve:_ops:dependency-reviewer` (READ-ONLY) | confidence-scoring |
| API contracts | `evolve:_ops:api-contract-reviewer` (READ-ONLY) | confidence-scoring |
| Rules curation | `evolve:_meta:rules-curator` | rule-audit, sync-rules |
| Orchestration / what-to-run | `evolve:_meta:evolve-orchestrator` | confidence-scoring |
| Research current best practices | `evolve:_ops:best-practices-researcher` | confidence-scoring |
| Research deps / CVEs / infra patterns | `evolve:_ops:dependency-researcher` / `security-researcher` / `infra-pattern-researcher` | confidence-scoring |
| Competitive design research | `evolve:_ops:competitive-design-researcher` | confidence-scoring |

### Scope boundaries (HARD rules)

- `laravel-developer` touches ONLY `backend/` — never `frontend/`
- `nextjs-developer` touches ONLY `frontend/` — never `backend/`
- `prototype-builder` touches ONLY `prototypes/` — never `backend/` or `frontend/`
- `postgres-architect` touches ONLY `backend/database/migrations/` and DB-related service files
- READ-ONLY agents (no Write/Edit): `repo-researcher`, `code-reviewer`, `security-auditor`, `architect-reviewer`, `performance-reviewer`, `dependency-reviewer`, `db-reviewer`, `api-contract-reviewer`, `ui-polish-reviewer`, `accessibility-reviewer`, `laravel-architect`, `nextjs-architect`, all researchers, all designers except prototype-builder

### Common workflows

**New feature (full-stack):**
1. `evolve:_product:systems-analyst` → requirements contract via `evolve:requirements-intake`
2. `evolve:_core:repo-researcher` → map existing code
3. `evolve:_product:product-manager` → PRD if user-facing (via `evolve:prd`)
4. `evolve:brainstorming` if complexity ≥7
5. `evolve:_design:creative-director` + `evolve:_design:prototype-builder` if UI feature → `evolve:prototype`
6. `evolve:writing-plans` → phased plan
7. `evolve:stacks/laravel:laravel-developer` → backend
8. `evolve:stacks/nextjs:nextjs-developer` → frontend
9. `evolve:_design:ui-polish-reviewer` → drift check
10. `evolve:_core:code-reviewer` → review
11. `evolve:_core:quality-gate-reviewer` → final ≥9 gate

**Bug fix:**
1. `evolve:_core:root-cause-debugger` via `evolve:systematic-debugging`
2. `evolve:tdd` regression test
3. `evolve:_core:code-reviewer`
4. `evolve:_core:quality-gate-reviewer`

**Brand reset / new product:**
1. `evolve:_design:creative-director` → direction
2. `evolve:_design:prototype-builder` → materialize via `evolve:brandbook` skill in `prototypes/_brandbook/`
3. `evolve:_design:copywriter` + `evolve:_design:accessibility-reviewer` review
4. User approval → brandbook becomes source-of-truth for all subsequent `evolve:prototype` invocations

### Mandatory subagent instructions

Every subagent prompt MUST include:

> ANTI-HALLUCINATION: Do not invent files, commands, or contracts that don't exist. Verify every claim with grep/read before reporting.
> CONFIDENCE-DISCIPLINE: Score your output via `evolve:confidence-scoring` before claiming done. <9 means not done unless `/evolve-override` was issued with reason.
> ZERO DEAD CODE: Every function/struct/variant/method you create MUST have at least one LIVE call site.

## Verification expectations

- `cd backend && ./vendor/bin/pest` — Pest tests (REQUIRED)
- `cd backend && ./vendor/bin/pint` — code style (REQUIRED, 0 changes)
- `cd backend && ./vendor/bin/phpstan analyse` — static analysis (REQUIRED, level max)
- `cd frontend && npm run typecheck` — TypeScript (REQUIRED)
- `cd frontend && npm test` — Vitest (REQUIRED)
- `cd frontend && npm run lint` — ESLint (REQUIRED)
- `cd frontend && npm run build` — Next.js build (REQUIRED before merge)
- `npm audit && composer audit` — security (REQUIRED before merge)

## Auto-evolve triggers

The main agent MUST suggest `/evolve <phase>` to the user when:

1. `.claude/agents/` empty or no routing table → `/evolve-genesis`
2. New module/command/service created → `/evolve-adapt`
3. New major dependency → `/evolve-adapt`
4. Agent failed due to stale context → `/evolve-audit`
5. >10 files changed in session → `/evolve-audit`
6. Oldest `last-verified` >30 days → `/evolve-audit + /evolve-strengthen`
7. New rule file in `.claude/rules/` → `evolve:_meta:rules-curator` review
8. Override-rate >5% over last 100 entries → `/evolve-audit`

## Stack-fingerprint

```yaml
project-type: web-app
backend: laravel
frontend: nextjs
database: [postgres]
infra: [redis-cache, queue]
architecture: modular-monolith
design-workflow: html-prototypes
test-pyramid-emphasis: balanced
ci-cd-platform: github-actions
```

(Auto-generated by `evolve:stack-discovery`. Update via `/evolve-adapt` if stack changes.)
