# CLAUDE.md

> Generated by `evolve:genesis` for stack: **{{stack-summary}}**

This repository uses the strict Evolve Framework workflow.

## Mission

Deliver correct, minimal, verifiable changes for a **{{stack-summary}}** application.

## Non-negotiable rules

1. Explore first, then plan, then implement, then verify.
2. Do not invent files, commands, routes, events, DTOs, stores, SQL objects, or public contracts.
3. Reuse existing project patterns before creating new abstractions.
4. Keep layer boundaries explicit (see Scope boundaries section).
5. Do not move business logic into the UI because it is convenient.
6. Prefer incremental changes with reviewable stop points.
7. Do not say a task is done without evidence (`evolve:verification` skill).
8. **Never claim "works correctly" without running a verification command and showing its output.**
9. Every artifact MUST score ≥9 against its `*-quality` rubric.
10. Never use banned git commands (see `.claude/settings.json` deny-list).
11. Conventional Commits enforced via commitlint.
12. Pre-commit pipeline enforced via husky.
13. Zero dead code: every function/struct/variant MUST have ≥1 live call site.

## Project paths (authoritative)

{{paths}}

## Agent routing — who to dispatch for what

{{agent-roster}}

### Scope boundaries (HARD rules)

{{scope-boundaries}}

### Mandatory subagent instructions

Every subagent prompt MUST include:

> ANTI-HALLUCINATION: Do not invent files, commands, or contracts that don't exist. Verify every claim with grep/read before reporting.
> CONFIDENCE-DISCIPLINE: Score your output via `evolve:confidence-scoring` before claiming done. <9 means not done unless `/evolve-override` was issued with reason.
> ZERO DEAD CODE: Every function/struct/variant/method you create MUST have at least one LIVE call site.

## Verification expectations

(stack-specific commands; see Project paths section above)

## Auto-evolve triggers

The main agent MUST suggest `/evolve-<phase>` when:

1. `.claude/agents/` empty or no routing table → `/evolve-genesis`
2. New module/service created → `/evolve-adapt`
3. New major dependency → `/evolve-adapt`
4. Agent failed due to stale context → `/evolve-audit`
5. >10 files changed in session → `/evolve-audit`
6. Oldest `last-verified` >30 days → `/evolve-audit + /evolve-strengthen`
7. New rule file → `evolve:_meta:rules-curator` review
8. Override-rate >5% over last 100 entries → `/evolve-audit`
