# CLAUDE.md

> Generated by `supervibe:genesis` for stack: **{{stack-summary}}**.
> This host instruction file is user-owned outside Supervibe managed blocks.

This repository uses the Supervibe workflow. The same project may also contain
`AGENTS.md`, `GEMINI.md`, `.cursor/rules/*`, or `opencode.json`; keep shared
instructions provider-neutral and put host-specific details only where required.

## Mission

Deliver correct, minimal, verifiable changes for a **{{stack-summary}}** application.

## Non-negotiable Rules

1. Explore first, then plan, then implement, then verify.
2. Check project memory, semantic code search and code graph before non-trivial changes.
3. Do not invent files, commands, routes, events, DTOs, stores, SQL objects, or public contracts.
4. Reuse existing project patterns before creating new abstractions.
5. Keep layer boundaries explicit.
6. Prefer incremental changes with reviewable stop points.
7. Never claim "works correctly" without running a verification command and reporting the result.
8. Every artifact should score >=9 against its applicable Supervibe rubric before completion.
9. Zero dead code: every function, struct, variant, method, route, command or handler created must have a live call site or documented public API exception.
10. Preserve user-owned instructions outside Supervibe managed blocks.

## Project Paths

{{paths}}

## Selected Agent Routing

{{agent-roster}}

## Scope Boundaries

{{scope-boundaries}}

## Mandatory Agent Instructions

Every delegated agent prompt should include:

```text
ANTI-HALLUCINATION: Do not invent files, commands, or contracts that do not exist. Verify claims with grep/read/search evidence before reporting.
CONFIDENCE-DISCIPLINE: Score output via the applicable Supervibe rubric before claiming done. <9 means not done unless the user explicitly accepts the risk.
ZERO DEAD CODE: Every function/struct/variant/method/route/command/handler you create must have at least one live caller or a documented public API exception.
MEMORY-RAG-GRAPH: Use project memory, semantic code search, and code graph evidence before non-trivial changes.
```

## Verification Expectations

Use stack-specific commands from the Project Paths section. Keep genesis/setup verification separate from application build/test verification unless the user explicitly asks for both.

## Update Path

1. Plugin update: run `/supervibe-update` or the installer update command for this host.
2. Project artifact refresh: run `/supervibe-adapt` and review the dry-run diff.
3. Do not delete generated agents/rules/skills to refresh them; adapt handles diff-gated updates and preserves user-owned content.
